CREATE TABLE orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    created_at          TIMESTAMP                               NOT NULL,
    deleted_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE shipping_addresses (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id BIGINT                                  NOT NULL,
    street   VARCHAR(255)                            NOT NULL,
    city     VARCHAR(255)                            NOT NULL,
    zip_code VARCHAR(255)                            NOT NULL,
    country  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_shipping_addresses PRIMARY KEY (id),
    CONSTRAINT kf_shippingaddress_on_orders FOREIGN KEY (order_id) REFERENCES orders(id)
);