---
version: '3.8'

services:
#  ## SPRING BOOT APPS ##
#  order-service:
#    container_name: order-service
#    build: ./order-service
#    depends_on:
#      - pg-database
#
#  order-updater-service:
#    container_name: order-updater-service
#    build: ./order-updater-service
#    depends_on:
#      - kafka-node
#      - pg-database

  ## DATABASE ##
  pg-database:
    container_name: pg-database
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: order-service, order-updater-service
    ports:
      - "5432:5432"
    volumes:
      - ./database/init_databases.sh:/docker-entrypoint-initdb.d/init_databases.sh
      - ./database/pgdata:/var/lib/postgresql/data

#  ## Kafka ##
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      -  "22181:2181"
#
#  kafka:
#    image: confluentinc/cp-kafka:latest
#    depends_on:
#      - zookeeper
#    ports:
#      - "29092:29092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1