openapi: 3.0.3
info:
  description: Open API specification for Order service
  version: 0.0.1
  title: Order Api Service Specification
  contact:
    name: JAVA developer
    email: palivtom@fel.cvut.cz
tags:
  - name: Order
  - name: Cart
paths:
  /orders:
    post:
      tags:
        - Order
      summary: Create new order
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Order has been created, returns orderId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdLong'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /orders/{orderId}:
    put:
      tags:
        - Order
      summary: Update order by id
      operationId: updateOrder
      parameters:
        - in: path
          required: true
          name: orderId
          description: Id of updating order
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '204':
          description: Order has been updated
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - Order
      summary: Cancel order by id
      operationId: cancelOrder
      parameters:
        - in: path
          required: true
          name: orderId
          description: Id of searched order
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Order has been canceled
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /cart/add:
    post:
      tags:
        - Cart
      summary: Add product to cart
      operationId: addProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartItem'
      responses:
        '204':
          description: Item has been added to the cart
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /cart/remove:
    post:
      tags:
        - Cart
      summary: Remove product from cart
      operationId: removeProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartItem'
      responses:
        '204':
          description: Item has been removed from the cart
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  responses:
    BadRequest:
      description: Indicates a nonspecific client error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Exception'

    Unauthorized:
      description: Unauthorized request - sent when the client either provided invalid credentials.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Exception'

    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Exception'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Exception'

  schemas:
    Exception:
      type: object
      properties:
        code:
          type: integer
          example: 400
        title:
          type: string
          example: Wrong input parameter
        message:
          type: string
          example: Wrong parameter for endpoint '/example/endpoint', wrong endpointId value.

    Order:
      type: object
      properties:
        id:
          readOnly: true
          type: integer
          format: int64
        userId:
          readOnly: true
          type: string
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddress'
        createdAt:
          readOnly: true
          type: integer
          format: int64
        updatedAt:
          readOnly: true
          type: integer
          format: int64
        deletedAt:
          readOnly: true
          type: integer
          format: int64
          description: If order is canceled, this field is filled with date and time of canceling

    ShippingAddress:
      type: object
      required:
        - country
        - city
        - street
        - zipCode
      properties:
        country:
          type: string
        city:
          type: string
        street:
          type: string
        zipCode:
          type: string

    CartItem:
      type: object
      required:
        - productNo
        - quantity
      properties:
        productNo:
          type: string
        quantity:
          type: integer

    IdLong:
      type: object
      readOnly: true
      properties:
        id:
          type: integer
          format: int64