CREATE TABLE carts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             VARCHAR(36)                             NOT NULL,
    exported_at         TIMESTAMP,
    CONSTRAINT pk_carts PRIMARY KEY (id)
);

CREATE TABLE orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             VARCHAR(36)                             NOT NULL,
    cart_id             BIGINT,
    created_at          TIMESTAMP                               NOT NULL,
    deleted_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT fk_order_id FOREIGN KEY (cart_id) REFERENCES carts(id)
);

CREATE TABLE shipping_addresses (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id            BIGINT                                  NOT NULL,
    street              VARCHAR(255)                            NOT NULL,
    city                VARCHAR(255)                            NOT NULL,
    zip_code            VARCHAR(255)                            NOT NULL,
    country             VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_shipping_addresses PRIMARY KEY (id),
    CONSTRAINT fk_order_id FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE cart_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_no          VARCHAR(255)                            NOT NULL,
    original_price      INTEGER                                 NOT NULL,
    discount_price      INTEGER,
    quantity            INTEGER                                 NOT NULL,
    CONSTRAINT pk_cart_items PRIMARY KEY (id)
);

CREATE TABLE cart_items_carts (
    cart_id                 BIGINT                              NOT NULL,
    cart_item_id            BIGINT                              NOT NULL,
    CONSTRAINT pk_cart_items_carts PRIMARY KEY (cart_item_id),
    CONSTRAINT fk_cart_id FOREIGN KEY (cart_id) REFERENCES carts(id),
    CONSTRAINT fk_cart_item_id FOREIGN KEY (cart_item_id) REFERENCES cart_items(id)
);