CREATE TABLE orders_view (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    shipping_address_id BIGINT,
    street              VARCHAR(255),
    city                VARCHAR(255),
    zip_code            VARCHAR(255),
    country             VARCHAR(255),
    created_at          TIMESTAMP                               NOT NULL,
    deleted_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);