CREATE TABLE carts_view (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             VARCHAR(36)                             NOT NULL,
    price_sum           INTEGER                                 NOT NULL,
    item_count          INTEGER                                 NOT NULL,
    exported_at         TIMESTAMP,
    CONSTRAINT pk_carts PRIMARY KEY (id)
);

CREATE TABLE orders_view (
    id                  BIGINT                                  NOT NULL,
    user_id             VARCHAR(36)                             NOT NULL,
    cart_id             BIGINT,
    shipping_address_id BIGINT UNIQUE,
    street              VARCHAR(255),
    city                VARCHAR(255),
    zip_code            VARCHAR(255),
    country             VARCHAR(255),
    created_at          TIMESTAMP                               NOT NULL,
    deleted_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT fk_order_id FOREIGN KEY (cart_id) REFERENCES carts_view(id)
);

CREATE TABLE cart_items_view (
    id                  BIGINT                                  NOT NULL,
    cart_id             BIGINT,
    product_no          VARCHAR(255)                            NOT NULL,
    original_price      INTEGER                                 NOT NULL,
    discount_price      INTEGER,
    quantity            INTEGER                                 NOT NULL,
    CONSTRAINT pk_cart_items PRIMARY KEY (id),
    CONSTRAINT fk_cart_id FOREIGN KEY (cart_id) REFERENCES carts_view(id)
);

CREATE TABLE cart_items_raw (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_no          VARCHAR(255)                            NOT NULL,
    original_price      INTEGER                                 NOT NULL,
    discount_price      INTEGER,
    quantity            INTEGER                                 NOT NULL,
    CONSTRAINT pk_cart_items_raw PRIMARY KEY (id)
);